from __future__ import annotations

import hashlib
from pathlib import Path

from research_memory_gateway.conversations.models import (
    ExportSessionRef,
    NormalizedConversation,
    NormalizedMessage,
)
from research_memory_gateway.conversations.vault_writer import (
    AUTOGEN_BEGIN,
    AUTOGEN_END,
    MAX_FILENAME_BYTES,
    ObsidianConversationWriter,
)


def test_writer_preserves_manual_section_and_emits_candidate(tmp_path: Path) -> None:
    writer = ObsidianConversationWriter(tmp_path / "vault")
    ref = ExportSessionRef(
        conversation_id="conv-p4-12345678",
        title="Chemical Synthesis Review",
        cwd="G:/LLM/memory",
        updated_at="2026-09-12T10:00:00Z",
        source_entry="files/0001/rollout.jsonl",
        source_size_bytes=200,
        source_sha256="abc",
    )
    conv = NormalizedConversation(
        ref=ref,
        archive_path="archive.zip",
        archive_sha256="hash",
        created_at="2026-09-12T10:00:00Z",
        session_meta={},
        messages=[
            NormalizedMessage(
                ordinal=1,
                timestamp="2026-09-12T10:00:00Z",
                role="user",
                text="Target compound yield 92% at 324 nm",
            ),
            NormalizedMessage(
                ordinal=2,
                timestamp="2026-09-12T10:00:01Z",
                role="assistant",
                phase="final_answer",
                text="Reaction duration 60 min confirmed.",
            ),
        ],
    )

    # 1. 首次写入
    out_path = writer.write(conv)
    initial_text = out_path.read_text(encoding="utf-8")
    assert AUTOGEN_BEGIN in initial_text
    assert AUTOGEN_END in initial_text
    assert "projects:\n- research-memory-gateway" in initial_text
    assert "timeline:\n- 2026-09" in initial_text

    initial_hash = hashlib.sha256(initial_text.encode("utf-8")).hexdigest()

    # 2. 幂等性：再次相同写入，hash 完全一致
    writer.write(conv)
    assert hashlib.sha256(out_path.read_text(encoding="utf-8").encode("utf-8")).hexdigest() == initial_hash

    # 3. 人工增加笔记和相关链接
    custom_manual = "## 人工补充与关联笔记 (Related & Notes)\n\n- [[Project Alpha]]\n- 重要科研决策：采用柱层析纯化\n"
    parts = initial_text.split(AUTOGEN_END)
    manual_edited_text = f"{parts[0]}{AUTOGEN_END}\n\n{custom_manual}"
    out_path.write_text(manual_edited_text, encoding="utf-8")

    # 4. 机器再次更新：保留人工内容
    writer.write(conv)
    updated_text = out_path.read_text(encoding="utf-8")
    assert "[[Project Alpha]]" in updated_text
    assert "重要科研决策：采用柱层析纯化" in updated_text
    assert "Target compound yield 92% at 324 nm" in updated_text

    # 5. 候选写入 candidate
    candidate_path = writer.write_candidate(conv)
    assert candidate_path.name.endswith(".candidate.md")
    assert candidate_path.exists()
    assert out_path.exists()


def test_writer_caps_multibyte_filename_by_utf8_bytes(tmp_path: Path) -> None:
    writer = ObsidianConversationWriter(tmp_path / "vault")
    ref = ExportSessionRef(
        conversation_id="019ea2ad-9a74-75c2-bf10-4246ca00ab25",
        title="使用学术研究套件阅读博士课题并查找文献验证高水平论文投稿可行性" * 12,
        cwd="D:/Partition/F/Study",
        updated_at="2026-06-07T10:00:00Z",
        source_entry="files/0001/rollout.jsonl",
        source_size_bytes=100,
        source_sha256="abc",
    )
    conv = NormalizedConversation(
        ref=ref,
        archive_path="archive.zip",
        archive_sha256="hash",
        created_at="2026-06-07T10:00:00Z",
        session_meta={},
        messages=[
            NormalizedMessage(
                ordinal=1,
                timestamp="2026-06-07T10:00:00Z",
                role="user",
                text="long title regression",
            )
        ],
    )

    out_path = writer.write(conv)
    assert len(out_path.name.encode("utf-8")) <= MAX_FILENAME_BYTES
    assert out_path.name.endswith(" - 019ea2ad.md")
    assert out_path.exists()


def test_managed_hash_stability_under_manual_edits() -> None:
    from research_memory_gateway.conversations.vault_writer import (
        compute_managed_hash,
        compute_manual_hash,
        parse_managed_regions,
    )

    doc_base = (
        "---\n"
        "type: ai-conversation\n"
        "source: codex\n"
        "conversation_id: conv-12345678\n"
        "created: '2026-09-12'\n"
        "projects:\n"
        "- test-proj\n"
        "---\n\n"
        "<!-- BEGIN AUTOGENERATED CONTENT: DO NOT EDIT THIS BLOCK DIRECTLY -->\n\n"
        "# Title\n\n"
        "## 背景\n\n"
        "- 工作目录：`/tmp`\n\n"
        "<!-- END AUTOGENERATED CONTENT -->\n\n"
        "## 人工补充与关联笔记 (Related & Notes)\n\n"
        "- [[Note A]]\n"
    )

    base_managed_hash = compute_managed_hash(doc_base)
    base_manual_hash = compute_manual_hash(doc_base)

    # 1. 仅修改人工正文（AUTOGEN_END 之后）
    doc_with_manual_edit = doc_base + "- [[Note B]] 追加更多重要结论\n"
    assert compute_managed_hash(doc_with_manual_edit) == base_managed_hash
    assert compute_manual_hash(doc_with_manual_edit) != base_manual_hash

    # 2. 在 frontmatter 增加人工字段 (如 manual_notes, x_manual_tag)
    doc_with_manual_fm = (
        "---\n"
        "type: ai-conversation\n"
        "source: codex\n"
        "conversation_id: conv-12345678\n"
        "created: '2026-09-12'\n"
        "projects:\n"
        "- test-proj\n"
        "manual_notes: '重要手写说明'\n"
        "x_manual_tags:\n"
        "- synthesis\n"
        "---\n\n"
        "<!-- BEGIN AUTOGENERATED CONTENT: DO NOT EDIT THIS BLOCK DIRECTLY -->\n\n"
        "# Title\n\n"
        "## 背景\n\n"
        "- 工作目录：`/tmp`\n\n"
        "<!-- END AUTOGENERATED CONTENT -->\n\n"
        "## 人工补充与关联笔记 (Related & Notes)\n\n"
        "- [[Note A]]\n"
    )
    assert compute_managed_hash(doc_with_manual_fm) == base_managed_hash
    assert compute_manual_hash(doc_with_manual_fm) != base_manual_hash

    # 3. 修改机器托管正文（AUTOGEN_BEGIN ... AUTOGEN_END 内部）
    doc_with_managed_body_edit = doc_base.replace("- 工作目录：`/tmp`", "- 工作目录：`/changed`")
    assert compute_managed_hash(doc_with_managed_body_edit) != base_managed_hash

    # 4. 修改机器托管 frontmatter 字段（如 conversation_id 或 source）
    doc_with_managed_fm_edit = doc_base.replace("conversation_id: conv-12345678", "conversation_id: conv-modified")
    assert compute_managed_hash(doc_with_managed_fm_edit) != base_managed_hash


def test_writer_preserves_manual_frontmatter_and_parent_thread(tmp_path: Path) -> None:
    writer = ObsidianConversationWriter(tmp_path / "vault")
    ref = ExportSessionRef(
        conversation_id="conv-child-9999",
        title="Child Conversation",
        cwd="G:/LLM/memory",
        updated_at="2026-09-12T12:00:00Z",
        source_entry="files/0002/rollout.jsonl",
        source_size_bytes=300,
        source_sha256="xyz",
    )
    conv = NormalizedConversation(
        ref=ref,
        archive_path="archive.zip",
        archive_sha256="hash",
        created_at="2026-09-12T12:00:00Z",
        session_meta={"parent_thread_id": "01a08c1c-b49b-70a2-b1a4-cad68e4b1cd4"},
        messages=[
            NormalizedMessage(
                ordinal=1,
                timestamp="2026-09-12T12:00:00Z",
                role="user",
                text="Please continue from parent thread",
            ),
        ],
    )

    out_path = writer.write(conv)
    text = out_path.read_text(encoding="utf-8")
    assert "parent_thread_id: 01a08c1c-b49b-70a2-b1a4-cad68e4b1cd4" in text
    assert "- 父级线程：`01a08c1c-b49b-70a2-b1a4-cad68e4b1cd4`" in text

    # 用户手动添加 frontmatter
    custom_fm_text = text.replace(
        "timeline:\n- 2026-09",
        "timeline:\n- 2026-09\nmanual_decision: confirmed-remediation\nx_tags:\n- memory\n- child-thread",
    )
    out_path.write_text(custom_fm_text, encoding="utf-8")

    # 机器再次覆写更新
    writer.write(conv)
    updated_text = out_path.read_text(encoding="utf-8")
    assert "manual_decision: confirmed-remediation" in updated_text
    assert "x_tags:\n- memory\n- child-thread" in updated_text
    assert "- 父级线程：`01a08c1c-b49b-70a2-b1a4-cad68e4b1cd4`" in updated_text

