from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock
import pytest

from research_memory_gateway.conversations.chunking import (
    HeadingChunker,
    compute_embedding_identity,
)
from research_memory_gateway.conversations.index import (
    ConversationIndexDatabase,
    SearchResult,
)

SAMPLE_MD = """---
type: ai-conversation
source: codex
conversation_id: 11111111-2222-3333-4444-555555555555
created: '2026-09-10'
updated: '2026-09-10'
projects:
- research-memory-gateway
timeline:
- 2026-09
---

<!-- BEGIN AUTOGENERATED CONTENT: DO NOT EDIT THIS BLOCK DIRECTLY -->

# Prototype Conversation

## 背景

- 工作目录：`G:\\LLM\\memory`
- 会话来源：`user`

## 用户目标

<!-- source ordinal=2 message_id=msg-user turn_id=turn-1 -->
### 用户

Keep exact path G:\\LLM\\memory and 324 nm.

## 工具活动

| ordinal | 方向 | 工具 | call_id | 字符数 | SHA-256 | 摘要 |
|---:|---|---|---|---:|---|---|
| 4 | call | exec_command | call-1 | 42 | `abc` | ERROR_NO_SYSTEM_RESOURCES 35984 |

## 最终结果

<!-- source ordinal=8 message_id=msg-assistant turn_id=turn-1 -->
### 助手 / final_answer

Result preserves 60 min.

<!-- END AUTOGENERATED CONTENT -->

## 人工补充与关联笔记 (Related & Notes)

自定义笔记
"""


def test_heading_chunking(tmp_path: Path) -> None:
    md_file = tmp_path / "sample.md"
    md_file.write_text(SAMPLE_MD, encoding="utf-8")

    chunker = HeadingChunker()
    frontmatter, chunks = chunker.chunk_file(md_file)

    assert frontmatter["conversation_id"] == "11111111-2222-3333-4444-555555555555"
    assert len(chunks) >= 4

    user_chunk = next(c for c in chunks if "324 nm" in c.content)
    assert "用户目标" in user_chunk.heading_path or "用户" in user_chunk.heading_path
    assert len(user_chunk.source_anchors) > 0
    assert user_chunk.source_anchors[0]["ordinal"] == "2"
    assert user_chunk.source_anchors[0]["message_id"] == "msg-user"


def test_index_fts_exact_queries_and_rebuild(tmp_path: Path) -> None:
    md_file = tmp_path / "sample.md"
    md_file.write_text(SAMPLE_MD, encoding="utf-8")
    db_path = tmp_path / "index.sqlite"

    # 1. 无 embedding 独立建立索引
    idx = ConversationIndexDatabase(db_path)
    count = idx.index_file(md_file)
    assert count > 0

    # 2. 精确查询
    res_324 = idx.search_fts("324 nm")
    assert len(res_324) > 0
    assert any("324 nm" in r.content for r in res_324)

    res_60 = idx.search_fts("60 min")
    assert len(res_60) > 0
    assert any("60 min" in r.content for r in res_60)

    res_err = idx.search_fts("ERROR_NO_SYSTEM_RESOURCES")
    assert len(res_err) > 0

    res_path = idx.search_fts('"G:\\LLM\\memory"')
    assert len(res_path) > 0

    # 3. 按 conversation_id 过滤
    res_scoped = idx.search_fts("324 nm", conversation_id="11111111-2222-3333-4444-555555555555")
    assert len(res_scoped) > 0
    res_none = idx.search_fts("324 nm", conversation_id="wrong-id")
    assert len(res_none) == 0

    # 4. 删除数据库后完全从 Markdown 重建
    db_path.unlink()
    idx_rebuilt = ConversationIndexDatabase(db_path)
    rebuilt_chunks = idx_rebuilt.rebuild_from_markdown([md_file])
    assert rebuilt_chunks == count
    assert len(idx_rebuilt.search_fts("324 nm")) > 0


def test_embedding_identity_cache_and_dimension_guard(tmp_path: Path) -> None:
    md_file = tmp_path / "sample.md"
    md_file.write_text(SAMPLE_MD, encoding="utf-8")
    db_path = tmp_path / "index_embed.sqlite"

    mock_client = MagicMock()
    mock_client.enabled = True
    mock_client.model = "bge-m3"
    mock_client.embed.side_effect = lambda text: [0.1] * 1024

    idx = ConversationIndexDatabase(db_path, embedding_client=mock_client)
    idx.index_file(md_file)

    call_count_1 = mock_client.embed.call_count
    assert call_count_1 > 0

    # 再次相同索引：因为 embedding_identity 未变，复用 cache，不再重复调 embed
    idx.index_file(md_file)
    assert mock_client.embed.call_count == call_count_1

    # embedding version 改变：内容未变也必须生成新的 identity 并重新 embedding
    idx_v2 = ConversationIndexDatabase(db_path, embedding_client=mock_client, embedding_version="v2")
    assert idx_v2.check_changed_reason(md_file) == "embedding_identity_changed"
    idx_v2.index_file(md_file)
    assert mock_client.embed.call_count == call_count_1 * 2
    assert idx_v2.check_changed_reason(md_file) == "unchanged"
    assert idx_v2.index_metadata_for_file(md_file)["embedding_version"] == "v2"

    # Roll back to v1.  Historical v1 cache exists, but live sections are v2,
    # so this must be an activation change rather than "unchanged".  Reindex
    # switches the live identities back without any new embedding call.
    idx_v1_again = ConversationIndexDatabase(db_path, embedding_client=mock_client, embedding_version="v1")
    assert idx_v1_again.check_changed_reason(md_file) == "embedding_activation_changed"
    before_rollback = mock_client.embed.call_count
    idx_v1_again.index_file(md_file)
    assert mock_client.embed.call_count == before_rollback
    assert idx_v1_again.check_changed_reason(md_file) == "unchanged"
    assert idx_v1_again.index_metadata_for_file(md_file)["embedding_version"] == "v1"

    _, expected_v1 = idx_v1_again.chunker.chunk_file(
        md_file, embedding_model="bge-m3", embedding_version="v1"
    )
    with idx_v1_again._connect() as conn:
        live = conn.execute(
            "SELECT id, embedding_identity FROM conversation_sections ORDER BY chunk_index"
        ).fetchall()
    assert [row["embedding_identity"] for row in live] == [c.embedding_identity for c in expected_v1]

    # Vector search is bound to the live identity + active model/version, so
    # retained v2 cache rows cannot duplicate live candidates.
    vector_results = idx_v1_again.search_vector([0.1] * 1024, limit=100)
    assert len(vector_results) == len(expected_v1)
    assert len({r.section_id for r in vector_results}) == len(vector_results)

    # Changing only one chunk must issue exactly one new embedding request.
    before_one_change = mock_client.embed.call_count
    md_file.write_text(SAMPLE_MD.replace("324 nm", "325 nm"), encoding="utf-8")
    idx_v1_again.index_file(md_file)
    assert mock_client.embed.call_count == before_one_change + 1

    # 验证维度不匹配保护
    mock_client_wrong_dim = MagicMock()
    mock_client_wrong_dim.enabled = True
    mock_client_wrong_dim.model = "bge-m3"
    mock_client_wrong_dim.embed.side_effect = lambda text: [0.1] * 512

    new_md = tmp_path / "new.md"
    new_md.write_text(SAMPLE_MD.replace("11111111", "22222222").replace("324 nm", "400 nm"), encoding="utf-8")

    idx_wrong = ConversationIndexDatabase(db_path, embedding_client=mock_client_wrong_dim)
    with pytest.raises(ValueError, match="Embedding dimension mismatch"):
        idx_wrong.index_file(new_md)


def test_dry_run_mode(tmp_path: Path) -> None:
    md_file = tmp_path / "sample.md"
    md_file.write_text(SAMPLE_MD, encoding="utf-8")
    db_path = tmp_path / "index_dry.sqlite"

    idx = ConversationIndexDatabase(db_path)
    chunks_count = idx.index_file(md_file, dry_run=True)
    assert chunks_count > 0

    # 数据库中不应有记录
    assert len(idx.search_fts("324 nm")) == 0


def test_parent_thread_indexing_and_search(tmp_path: Path) -> None:
    child_md = (
        "---\n"
        "type: ai-conversation\n"
        "source: codex\n"
        "conversation_id: 01a08fdc-6da5-7f93-9119-ff79d9fea710\n"
        "parent_thread_id: 01a08c1c-b49b-70a2-b1a4-cad68e4b1cd4\n"
        "thread_source: user\n"
        "created: '2026-09-11'\n"
        "---\n\n"
        "<!-- BEGIN AUTOGENERATED CONTENT: DO NOT EDIT THIS BLOCK DIRECTLY -->\n\n"
        "# TOC QA Session\n\n"
        "## 背景\n\n"
        "- 工作目录：`G:\\LLM\\memory`\n"
        "- 会话来源：`user`\n"
        "- 父级线程：`01a08c1c-b49b-70a2-b1a4-cad68e4b1cd4`\n\n"
        "## 关键原始内容\n\n"
        "<!-- source ordinal=1 message_id=msg-001 turn_id=turn-1 -->\n"
        "### 用户\n\n"
        "Please inspect Vertex_TOC_Focused_20260911_v1\\TOC_Focused.png and check Fe3+ concentration.\n\n"
        "<!-- END AUTOGENERATED CONTENT -->\n\n"
        "## 人工补充与关联笔记 (Related & Notes)\n"
    )
    md_file = tmp_path / "child.md"
    md_file.write_text(child_md, encoding="utf-8")
    db_path = tmp_path / "index_parent.sqlite"
    idx = ConversationIndexDatabase(db_path)
    idx.index_file(md_file)

    # 1. 经由 FTS 直接检索父线程 UUID
    results_fts_uuid = idx.search_fts("01a08c1c-b49b-70a2-b1a4-cad68e4b1cd4")
    assert len(results_fts_uuid) > 0
    assert results_fts_uuid[0].parent_thread_id == "01a08c1c-b49b-70a2-b1a4-cad68e4b1cd4"

    # 2. 带 parent_thread_id 过滤
    results_filtered = idx.search_fts("Fe3+", parent_thread_id="01a08c1c-b49b-70a2-b1a4-cad68e4b1cd4")
    assert len(results_filtered) > 0
    assert results_filtered[0].conversation_id == "01a08fdc-6da5-7f93-9119-ff79d9fea710"

    # 3. 错误 parent_thread_id 返回空
    results_wrong = idx.search_fts("Fe3+", parent_thread_id="00000000-0000-0000-0000-000000000000")
    assert len(results_wrong) == 0


def test_check_changed_and_index_run_logging(tmp_path: Path) -> None:
    md_file = tmp_path / "sample.md"
    md_file.write_text(SAMPLE_MD, encoding="utf-8")
    db_path = tmp_path / "index_changed.sqlite"

    idx = ConversationIndexDatabase(db_path)
    # 未建索引时：check_changed 为 True
    assert idx.check_changed(md_file) is True

    # 建索引后：check_changed 为 False
    idx.index_file(md_file)
    assert idx.check_changed(md_file) is False

    # 人工区域属于 conversation 搜索知识：不会影响 import conflict hash，
    # 但必须让派生索引变 stale，并在 reindex 后可检索。
    manual_text = SAMPLE_MD + "\n\n人工新增笔记 UNIQUE_MANUAL_SEARCH_TERM\n"
    md_file.write_text(manual_text, encoding="utf-8")
    assert idx.check_changed(md_file) is True
    idx.index_file(md_file)
    assert idx.check_changed(md_file) is False
    assert len(idx.search_fts("UNIQUE_MANUAL_SEARCH_TERM")) > 0

    # 修改 machine-managed 内容后：check_changed 为 True
    md_file.write_text(manual_text.replace("324 nm", "325 nm"), encoding="utf-8")
    assert idx.check_changed(md_file) is True

    # 记录 index run
    idx.record_index_run(
        run_at="2026-09-12T12:00:00Z",
        indexed_files=1,
        skipped_files=2,
        total_chunks=5,
        embedded_chunks=0,
        model="none",
        status="success",
    )
    with idx._connect() as conn:
        row = conn.execute("SELECT * FROM conversation_index_runs ORDER BY id DESC LIMIT 1").fetchone()
        assert row is not None
        assert row["indexed_files"] == 1
        assert row["skipped_files"] == 2
        assert row["status"] == "success"


def test_chunker_oversize_split_inherits_source_anchor(tmp_path: Path) -> None:
    large_paragraph = "Fe3+ catalyst yield analysis. " * 80  # ~2400 字符，超过 1500
    doc = (
        "---\n"
        "type: ai-conversation\n"
        "conversation_id: conv-oversize-1\n"
        "---\n\n"
        "<!-- BEGIN AUTOGENERATED CONTENT: DO NOT EDIT THIS BLOCK DIRECTLY -->\n\n"
        "# Large Doc\n\n"
        "## 关键原始内容\n\n"
        "<!-- source ordinal=42 message_id=msg-oversize turn_id=turn-9 -->\n"
        "### 用户\n\n"
        f"{large_paragraph}\n\n"
        f"{large_paragraph}\n\n"
        "<!-- END AUTOGENERATED CONTENT -->\n"
    )
    chunker = HeadingChunker(max_chunk_chars=1500)
    _, chunks = chunker.chunk_text(doc)

    # 验证确实被拆分成了多个 chunk
    user_chunks = [c for c in chunks if "Fe3+" in c.content]
    assert len(user_chunks) >= 2
    for c in user_chunks:
        assert len(c.content) <= 1500
        assert len(c.source_anchors) == 1
        assert c.source_anchors[0]["ordinal"] == "42"
        assert c.source_anchors[0]["message_id"] == "msg-oversize"


@pytest.mark.parametrize(
    "payload",
    [
        "A" * 5000,
        "\n".join(["| col | value |", "|---|---|"] + [f"| {i} | {'x' * 80} |" for i in range(80)]),
        "```text\n" + ("payload-without-breaks-" * 300) + "\n```",
        "中文长文本。" * 1000,
        "single-line-" * 800,
    ],
    ids=["paragraph", "markdown-table", "code-block", "chinese", "single-line"],
)
def test_chunker_hard_upper_bound_for_oversize_shapes(payload: str) -> None:
    doc = (
        "---\nconversation_id: cap-test\n---\n\n"
        "# Doc\n\n"
        "<!-- source ordinal=7 message_id=msg-cap turn_id=turn-cap -->\n"
        "## Payload\n\n"
        f"{payload}\n"
    )
    chunker = HeadingChunker(max_chunk_chars=1500)
    _, chunks = chunker.chunk_text(doc)
    assert chunks
    assert all(len(chunk.content) <= 1500 for chunk in chunks)
    assert all(chunk.source_anchors[0]["ordinal"] == "7" for chunk in chunks)


def test_embedding_accounting_trustworthy(tmp_path: Path) -> None:
    md_file = tmp_path / "sample.md"
    md_file.write_text(SAMPLE_MD, encoding="utf-8")
    db_path = tmp_path / "index_embed_accounting.sqlite"

    mock_client = MagicMock()
    mock_client.enabled = True
    mock_client.model = "bge-m3"
    mock_client.embed.side_effect = lambda text: [0.1] * 1024

    idx = ConversationIndexDatabase(db_path, embedding_client=mock_client)

    # 1. 首次索引：应记录 new_embedding_requests，cache_reused 为 0
    chunks_count = idx.index_file(md_file)
    assert chunks_count > 0
    stats1 = idx.embedding_stats
    assert stats1["new_embedding_requests"] == chunks_count
    assert stats1["cache_reused"] == 0
    assert stats1["failures"] == 0
    assert stats1["dimension_mismatches"] == 0

    idx.record_index_run(
        run_at="2026-09-12T12:00:00Z",
        indexed_files=1,
        skipped_files=0,
        total_chunks=chunks_count,
        embedded_chunks=stats1["new_embedding_requests"],
        cache_reused_chunks=stats1["cache_reused"],
        failed_chunks=stats1["failures"],
        model="bge-m3",
        status="success",
    )
    with idx._connect() as conn:
        row = conn.execute("SELECT * FROM conversation_index_runs ORDER BY id DESC LIMIT 1").fetchone()
        assert row["total_chunks"] == chunks_count
        assert row["embedded_chunks"] == chunks_count
        assert row["cache_reused_chunks"] == 0

    # 2. 第二次索引（相同内容）：new_embedding_requests 应为 0，cache_reused 为 chunks_count
    idx.reset_embedding_stats()
    idx.index_file(md_file)
    stats2 = idx.embedding_stats
    assert stats2["new_embedding_requests"] == 0
    assert stats2["cache_reused"] == chunks_count
    assert stats2["failures"] == 0

    idx.record_index_run(
        run_at="2026-09-12T12:05:00Z",
        indexed_files=1,
        skipped_files=0,
        total_chunks=chunks_count,
        embedded_chunks=stats2["new_embedding_requests"],
        cache_reused_chunks=stats2["cache_reused"],
        failed_chunks=stats2["failures"],
        model="bge-m3",
        status="success",
    )
    with idx._connect() as conn:
        row = conn.execute("SELECT * FROM conversation_index_runs ORDER BY id DESC LIMIT 1").fetchone()
        assert row["embedded_chunks"] == 0
        assert row["cache_reused_chunks"] == chunks_count

    # 3. 修改单 chunk：恰好 1 个 new_embedding_request，其余 cache_reused
    idx.reset_embedding_stats()
    md_file.write_text(SAMPLE_MD.replace("324 nm", "325 nm"), encoding="utf-8")
    idx.index_file(md_file)
    stats3 = idx.embedding_stats
    assert stats3["new_embedding_requests"] == 1
    assert stats3["cache_reused"] == chunks_count - 1

    # 4. embedding 失败统计
    idx.reset_embedding_stats()
    mock_client.embed.side_effect = lambda text: None
    new_md = tmp_path / "new_fail.md"
    new_md.write_text(SAMPLE_MD.replace("11111111", "99999999").replace("324 nm", "500 nm"), encoding="utf-8")
    idx.index_file(new_md)
    stats4 = idx.embedding_stats
    assert stats4["new_embedding_requests"] == 0
    assert stats4["failures"] > 0

