from __future__ import annotations

import json
import sqlite3
from dataclasses import replace
from pathlib import Path

import pytest

from research_memory_gateway.conversations.manifest import ImportManifest
from research_memory_gateway.conversations.models import ExportSessionRef


def test_manifest_state_machine_and_migration(tmp_path: Path) -> None:
    db_path = tmp_path / "manifest.sqlite"

    # 1. 模拟一个旧版表（缺少新字段）
    conn = sqlite3.connect(db_path)
    conn.execute(
        """
        CREATE TABLE conversation_imports (
            conversation_id TEXT PRIMARY KEY,
            source_archive_path TEXT NOT NULL,
            source_archive_sha256 TEXT NOT NULL,
            source_entry TEXT NOT NULL,
            source_entry_sha256 TEXT NOT NULL,
            source_size_bytes INTEGER NOT NULL,
            output_path TEXT NOT NULL,
            output_sha256 TEXT NOT NULL,
            imported_at TEXT NOT NULL,
            parser_version TEXT NOT NULL,
            schema_version TEXT NOT NULL,
            embedding_model TEXT,
            status TEXT NOT NULL DEFAULT 'written'
        )
        """
    )
    conn.commit()
    conn.close()

    # 2. 初始化 ImportManifest，应自动执行 migration 增加新列
    manifest = ImportManifest(db_path)
    ref = ExportSessionRef(
        conversation_id="conv-p5-test",
        title="State Machine Session",
        cwd="G:/LLM/memory",
        updated_at="2026-09-12T12:00:00Z",
        source_entry="files/0001/rollout.jsonl",
        source_size_bytes=500,
        source_sha256="src_sha_original",
    )

    # 状态: new
    dec = manifest.decide(ref, archive_sha256="archive_sha_1")
    assert dec.status == "new"

    # 记录写入
    dummy_output = tmp_path / "note.md"
    dummy_output.write_text("dummy content", encoding="utf-8")
    manifest.record(
        ref,
        archive_path="archive.zip",
        archive_sha256="archive_sha_1",
        output_path=dummy_output,
        parent_thread_id="parent-001",
        attachment_inventory_hash="att_hash_1",
        status="written",
    )

    # 状态: unchanged
    dec = manifest.decide(ref, archive_sha256="archive_sha_1", attachment_inventory_hash="att_hash_1")
    assert dec.status == "unchanged"
    assert dec.action == "skip"

    # 状态: changed_source
    ref_changed_src = replace(ref, source_sha256="src_sha_updated")
    dec = manifest.decide(ref_changed_src, archive_sha256="archive_sha_1")
    assert dec.status == "changed_source"
    assert dec.action == "write"

    # 状态: parser_upgrade (dry_run vs rebuild)
    dec_upgrade_dry = manifest.decide(ref, archive_sha256="archive_sha_1", parser_version="new-v2.0", dry_run=True)
    assert dec_upgrade_dry.status == "parser_upgrade"
    assert dec_upgrade_dry.action == "dry_run"

    dec_upgrade_rebuild = manifest.decide(ref, archive_sha256="archive_sha_1", parser_version="new-v2.0", dry_run=False)
    assert dec_upgrade_rebuild.status == "parser_upgrade"
    assert dec_upgrade_rebuild.action == "rebuild"

    # 状态: attachment_changed
    dec_att_changed = manifest.decide(ref, archive_sha256="archive_sha_1", attachment_inventory_hash="att_hash_2")
    assert dec_att_changed.status == "attachment_changed"
    assert dec_att_changed.action == "write"

    # 状态: output_missing
    dummy_output.unlink()
    dec_missing = manifest.decide(ref, archive_sha256="archive_sha_1")
    assert dec_missing.status == "output_missing"
    assert dec_missing.action == "write"

    # 状态: managed_output_modified
    dummy_output.write_text("tampered content", encoding="utf-8")
    dec_tampered = manifest.decide(ref, archive_sha256="archive_sha_1")
    assert dec_tampered.status == "managed_output_modified"
    assert dec_tampered.action == "conflict"

    # 状态: index_stale
    # 重写回合法 note，并记录为 written 状态，模拟已有 index 记录
    valid_note = (
        "---\n"
        "type: ai-conversation\n"
        "source: codex\n"
        "conversation_id: conv-p5-test\n"
        "---\n\n"
        "<!-- BEGIN AUTOGENERATED CONTENT: DO NOT EDIT THIS BLOCK DIRECTLY -->\n"
        "# Note\n"
        "<!-- END AUTOGENERATED CONTENT -->\n\n"
        "## 人工补充与关联笔记 (Related & Notes)\n"
    )
    dummy_output.write_text(valid_note, encoding="utf-8")
    manifest.record(
        ref,
        archive_path="archive.zip",
        archive_sha256="archive_sha_1",
        output_path=dummy_output,
        parent_thread_id="parent-001",
        status="written",
    )
    # 记录 indexing 完成
    manifest.record_indexing(
        ref.conversation_id,
        index_source_hash="old_index_hash",
        last_indexed_at="2026-09-12T12:00:00Z",
    )
    # 因为 index_source_hash != file_hash，应判定 index_stale
    dec_stale = manifest.decide(ref, archive_sha256="archive_sha_1", check_index=True)
    assert dec_stale.status == "index_stale"
    assert dec_stale.action == "index"

    # 状态: failed_retryable
    manifest.record(
        ref,
        archive_path="archive.zip",
        archive_sha256="archive_sha_1",
        output_path=dummy_output,
        status="failed_retryable",
        error="disk full",
    )
    dec_failed = manifest.decide(ref, archive_sha256="archive_sha_1")
    assert dec_failed.status == "failed_retryable"
    assert dec_failed.action == "write"

    # 导出 JSON
    json_export = tmp_path / "manifest.json"
    manifest.export_json(json_export)
    data = json.loads(json_export.read_text(encoding="utf-8"))
    assert len(data) == 1
    assert data[0]["parent_thread_id"] == "parent-001"
    assert data[0]["status"] == "failed_retryable"
    assert data[0]["error"] == "disk full"


def test_manifest_safe_failure_without_output_file(tmp_path: Path) -> None:
    db_path = tmp_path / "manifest.sqlite"
    manifest = ImportManifest(db_path)
    ref = ExportSessionRef(
        conversation_id="conv-fail-test",
        title="Failed Session",
        cwd="G:/LLM/memory",
        updated_at="2026-09-12T12:00:00Z",
        source_entry="files/0002/rollout.jsonl",
        source_size_bytes=100,
        source_sha256="src_sha_fail",
    )
    non_existent = tmp_path / "never_created.md"

    # 记录失败且文件不存在：绝不能抛出 FileNotFoundError
    manifest.record(
        ref,
        archive_path="archive.zip",
        archive_sha256="archive_sha_1",
        output_path=non_existent,
        status="failed_retryable",
        error="Parser crashed before file write",
    )

    dec = manifest.decide(ref, archive_sha256="archive_sha_1")
    assert dec.status == "failed_retryable"
    assert dec.action == "write"


def test_manifest_manual_region_edits_do_not_trigger_conflict(tmp_path: Path) -> None:
    db_path = tmp_path / "manifest.sqlite"
    manifest = ImportManifest(db_path)
    ref = ExportSessionRef(
        conversation_id="conv-manual-test",
        title="Manual Session",
        cwd="G:/LLM/memory",
        updated_at="2026-09-12T12:00:00Z",
        source_entry="files/0003/rollout.jsonl",
        source_size_bytes=100,
        source_sha256="src_sha_3",
    )
    note_path = tmp_path / "manual_note.md"
    initial_text = (
        "---\n"
        "type: ai-conversation\n"
        "source: codex\n"
        "conversation_id: conv-manual-test\n"
        "---\n\n"
        "<!-- BEGIN AUTOGENERATED CONTENT: DO NOT EDIT THIS BLOCK DIRECTLY -->\n\n"
        "# Manual Session\n\n"
        "## 背景\n\n"
        "- 工作目录：`/tmp`\n\n"
        "<!-- END AUTOGENERATED CONTENT -->\n\n"
        "## 人工补充与关联笔记 (Related & Notes)\n\n"
        "- [[Link A]]\n"
    )
    note_path.write_text(initial_text, encoding="utf-8")
    manifest.record(
        ref,
        archive_path="archive.zip",
        archive_sha256="archive_sha_1",
        output_path=note_path,
        status="written",
    )

    # 1. 用户仅修改人工区：decide 应该保持 unchanged，绝不能返回 conflict
    edited_manual_text = initial_text + "- 用户自定义追加笔记\n"
    note_path.write_text(edited_manual_text, encoding="utf-8")
    dec = manifest.decide(ref, archive_sha256="archive_sha_1")
    assert dec.status == "unchanged"
    assert dec.action == "skip"

    # 2. 用户修改了托管区：必须返回 conflict / managed_output_modified
    edited_managed_text = edited_manual_text.replace("- 工作目录：`/tmp`", "- 工作目录：`/tampered`")
    note_path.write_text(edited_managed_text, encoding="utf-8")
    dec_tampered = manifest.decide(ref, archive_sha256="archive_sha_1")
    assert dec_tampered.status == "managed_output_modified"
    assert dec_tampered.action == "conflict"

