from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any

import yaml

from research_memory_gateway.config import atomic_write_text

from .models import ExportSessionRef, NormalizedConversation, PARSER_VERSION, SCHEMA_VERSION

AUTOGEN_BEGIN = "<!-- BEGIN AUTOGENERATED CONTENT: DO NOT EDIT THIS BLOCK DIRECTLY -->"
AUTOGEN_END = "<!-- END AUTOGENERATED CONTENT -->"
DEFAULT_MANUAL_SECTION = "## 人工补充与关联笔记 (Related & Notes)\n\n<!-- 在此添加自定义笔记、研究决策或 Obsidian 反向链接 [[...]]，重新生成时会自动保留 -->\n"
MAX_FILENAME_BYTES = 240

MACHINE_FRONTMATTER_KEYS = {
    "type",
    "source",
    "source_system",
    "source_originator",
    "source_surface",
    "source_version",
    "model_provider",
    "model_name",
    "conversation_id",
    "created",
    "updated",
    "projects",
    "timeline",
    "topics",
    "source_hash",
    "archive_hash",
    "source_entry",
    "parser_version",
    "schema_version",
    "thread_source",
    "parent_thread_id",
    "agent_path",
    "completion_status",
}


def parse_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) >= 3:
            fm_text = parts[1]
            body = parts[2].lstrip("\r\n")
            try:
                data = yaml.safe_load(fm_text) or {}
                if isinstance(data, dict):
                    return data, body
            except Exception:
                pass
    return {}, text


def parse_managed_regions(text: str) -> tuple[dict[str, Any], str, str]:
    fm, body = parse_frontmatter(text)
    if AUTOGEN_END in body:
        parts = body.split(AUTOGEN_END, 1)
        before_end = parts[0]
        manual_content = parts[1].lstrip("\r\n")
        if AUTOGEN_BEGIN in before_end:
            _, managed_body = before_end.split(AUTOGEN_BEGIN, 1)
            managed_body = managed_body.strip()
        else:
            managed_body = before_end.strip()
    else:
        managed_body = body.strip()
        manual_content = ""
    return fm, managed_body, manual_content


def extract_manual_regions(text: str) -> tuple[dict[str, Any], str]:
    fm, _, manual_content = parse_managed_regions(text)
    manual_fm = {k: v for k, v in fm.items() if k not in MACHINE_FRONTMATTER_KEYS}
    return manual_fm, manual_content


def compute_managed_hash(text: str) -> str:
    fm, managed_body, _ = parse_managed_regions(text)
    machine_fm = {k: fm[k] for k in sorted(MACHINE_FRONTMATTER_KEYS) if k in fm}
    fm_json = json.dumps(machine_fm, sort_keys=True, ensure_ascii=False)
    hasher = hashlib.sha256()
    hasher.update(fm_json.encode("utf-8"))
    hasher.update(b"\n")
    hasher.update(managed_body.encode("utf-8"))
    return hasher.hexdigest()


def compute_manual_hash(text: str) -> str:
    manual_fm, manual_content = extract_manual_regions(text)
    fm_json = json.dumps(manual_fm, sort_keys=True, ensure_ascii=False)
    hasher = hashlib.sha256()
    hasher.update(fm_json.encode("utf-8"))
    hasher.update(b"\n")
    hasher.update(manual_content.strip().encode("utf-8"))
    return hasher.hexdigest()


class ObsidianConversationWriter:
    def __init__(self, root: str | Path, *, include_internal_messages: bool = False) -> None:
        self.root = Path(root)
        self.include_internal_messages = include_internal_messages

    def target_path_from_ref(self, ref: ExportSessionRef, created_at: str = "") -> Path:
        date = _date_part(created_at or ref.updated_at) or "unknown-date"
        year = date[:4] if re.fullmatch(r"\d{4}-\d{2}-\d{2}", date) else "unknown"
        clean_title = _safe_filename(ref.title or "Untitled")
        prefix = f"{date} - "
        suffix = f" - {ref.conversation_id[:8]}.md"
        title_budget = max(
            16,
            MAX_FILENAME_BYTES - len(prefix.encode("utf-8")) - len(suffix.encode("utf-8")),
        )
        clean_title = _truncate_utf8(clean_title, title_budget).rstrip(" .")
        if not clean_title:
            clean_title = hashlib.sha256((ref.title or "Untitled").encode("utf-8")).hexdigest()[:16]
        filename = f"{prefix}{clean_title}{suffix}"
        return self.root / "Conversations" / year / filename

    def target_path(self, conversation: NormalizedConversation) -> Path:
        return self.target_path_from_ref(conversation.ref, conversation.created_at)

    def write(
        self,
        conversation: NormalizedConversation,
        *,
        overwrite_managed: bool = True,
        path_override: str | Path | None = None,
    ) -> Path:
        path = Path(path_override) if path_override else self.target_path(conversation)
        if path_override:
            root_resolved = self.root.resolve()
            path_resolved = path.resolve()
            try:
                path_resolved.relative_to(root_resolved)
            except ValueError as exc:
                raise PermissionError(
                    f"Refusing conversation output outside writer root: {path_resolved}"
                ) from exc
            path = path_resolved
        manual_content = ""
        manual_frontmatter: dict[str, Any] = {}
        if path.exists():
            existing = path.read_text(encoding="utf-8")
            marker = f"conversation_id: {conversation.ref.conversation_id}"
            if marker not in existing:
                raise FileExistsError(f"Refusing to overwrite non-managed note: {path}")
            if not overwrite_managed:
                raise FileExistsError(f"Managed note already exists: {path}")
            manual_frontmatter, manual_content = extract_manual_regions(existing)
        path.parent.mkdir(parents=True, exist_ok=True)
        atomic_write_text(
            path,
            self.render(
                conversation,
                manual_content=manual_content,
                manual_frontmatter=manual_frontmatter,
            ),
        )
        return path

    def write_candidate(self, conversation: NormalizedConversation) -> Path:
        normal_path = self.target_path(conversation)
        candidate_path = normal_path.with_name(f"{normal_path.stem}.candidate.md")
        candidate_path.parent.mkdir(parents=True, exist_ok=True)
        atomic_write_text(candidate_path, self.render(conversation))
        return candidate_path

    def extract_manual_content(self, text: str) -> str:
        return extract_manual_regions(text)[1]

    def render(
        self,
        conversation: NormalizedConversation,
        *,
        manual_content: str = "",
        manual_frontmatter: dict[str, Any] | None = None,
    ) -> str:
        visible = [
            message
            for message in conversation.messages
            if self.include_internal_messages
            or (message.role in {"user", "assistant"} and not message.is_injected)
        ]
        internal_count = len(conversation.messages) - len(visible)
        users = [message for message in visible if message.role == "user"]
        assistants = [message for message in visible if message.role == "assistant"]
        final_answers = [message for message in assistants if message.phase == "final_answer"]
        completion_status = conversation.completion_status or ("complete" if final_answers else "incomplete_or_unknown")
        frontmatter = {
            "type": "ai-conversation",
            "source": "codex",
            "source_system": conversation.source_system or "codex",
            "source_originator": conversation.source_originator or None,
            "source_surface": conversation.source_surface or None,
            "source_version": conversation.source_version or None,
            "model_provider": conversation.model_provider or None,
            "model_name": conversation.model_name or None,
            "conversation_id": conversation.ref.conversation_id,
            "created": _date_part(conversation.created_at),
            "updated": _date_part(conversation.ref.updated_at),
            "projects": _infer_project(conversation.ref.cwd),
            "timeline": _infer_timeline(conversation.created_at),
            "topics": [],
            "source_hash": conversation.ref.source_sha256,
            "archive_hash": conversation.archive_sha256,
            "source_entry": conversation.ref.source_entry,
            "parser_version": PARSER_VERSION,
            "schema_version": SCHEMA_VERSION,
            "thread_source": conversation.thread_source,
            "parent_thread_id": conversation.parent_thread_id or None,
            "agent_path": conversation.agent_path or None,
            "completion_status": completion_status,
        }
        if manual_frontmatter:
            for k, v in manual_frontmatter.items():
                if k not in MACHINE_FRONTMATTER_KEYS:
                    frontmatter[k] = v
        yaml_text = yaml.safe_dump(
            frontmatter, allow_unicode=True, sort_keys=False, default_flow_style=False
        ).strip()
        lines = ["---", yaml_text, "---", "", AUTOGEN_BEGIN, "", f"# {conversation.ref.title}", ""]
        bg_lines = [
            "## 背景",
            "",
            f"- 工作目录：`{conversation.ref.cwd}`",
            f"- 会话来源：`{conversation.thread_source or 'unknown'}`",
        ]
        if conversation.parent_thread_id:
            bg_lines.append(f"- 父级线程：`{conversation.parent_thread_id}`")
        bg_lines.extend(
            [
                f"- 原始记录：`{conversation.ref.source_entry}`",
                f"- 可见消息：{len(visible)}；内部消息：{internal_count}；工具事件：{len(conversation.tools)}；附件引用：{len(conversation.attachments)}",
                "",
                "## 用户目标",
                "",
                users[0].text if users else "原始记录中没有可恢复的用户正文。",
                "",
                "## 过程与恢复说明",
                "",
                "消息顺序按 JSONL `ordinal` 恢复。`response_item/message` 作为消息主记录，",
                "`event_msg/item_completed` 中重复的 UserMessage/AgentMessage 不再次写入。",
                "system/developer 提示、reasoning、巨型 tool schema 与完整 tool stdout 默认不进入正文；",
                "它们保留在 immutable ZIP 中，并可由下面的 source entry 和 ordinal 回溯。",
                "",
            ]
        )
        lines.extend(bg_lines)
        if completion_status == "complete" and final_answers:
            lines.extend(["## 最终结果", "", final_answers[-1].text, ""])
        elif completion_status == "aborted":
            if assistants:
                lines.extend(["## 最后可见助手输出（任务中断）", "", assistants[-1].text, ""])
            lines.extend(
                [
                    "## 未解决问题",
                    "",
                    f"会话已被显式中止或中断（原因：{conversation.completion_reason or 'turn_aborted'}）；不能把过程性输出视为最终结论。",
                    "",
                ]
            )
        elif assistants:
            lines.extend(
                [
                    "## 最后可见助手输出（非 final）",
                    "",
                    assistants[-1].text,
                    "",
                    "## 未解决问题",
                    "",
                    "未找到 `phase=final_answer` 的助手消息。会话可能中断、转入其他分支，或导出时尚未完成；不能把上面的过程性输出视为最终结论。",
                    "",
                ]
            )
        else:
            lines.extend(
                [
                    "## 未解决问题",
                    "",
                    "原始记录中没有可恢复的助手最终答复。",
                    "",
                ]
            )
        if conversation.tools:
            lines.extend(["## 工具活动", "", "| ordinal | 方向 | 工具 | call_id | 字符数 | SHA-256 | 摘要 |", "|---:|---|---|---|---:|---|---|"])
            for item in conversation.tools:
                lines.append(
                    "| {ordinal} | {direction} | {name} | {call_id} | {chars} | `{digest}` | {excerpt} |".format(
                        ordinal=item.ordinal,
                        direction=item.direction,
                        name=_table(item.name or item.event_type),
                        call_id=_table(item.call_id),
                        chars=item.payload_chars,
                        digest=item.payload_hash,
                        excerpt=_table(item.excerpt),
                    )
                )
            lines.append("")
        if conversation.attachments:
            lines.extend(["## 附件引用", "", "| ordinal | 类型 | 定位 | SHA-256 | 大小 |", "|---:|---|---|---|---:|"])
            for item in conversation.attachments:
                lines.append(
                    f"| {item.ordinal} | {_table(item.content_type)} | {_table(item.locator)} | `{item.content_hash}` | {item.size_bytes or ''} |"
                )
            lines.extend(["", "附件未自动复制。`embedded-data` 只记录哈希和大小，原值仍在 ZIP 中。", ""])
        lines.extend(["## 关键原始内容", ""])
        for message in visible:
            role = {"user": "用户", "assistant": "助手"}.get(message.role, message.role)
            phase = f" / {message.phase}" if message.phase else ""
            lines.extend(
                [
                    f"<!-- source ordinal={message.ordinal} message_id={message.message_id} turn_id={message.turn_id} -->",
                    f"### {role}{phase}",
                    "",
                    message.text,
                    "",
                ]
            )
        lines.extend(
                [
                    "## Source",
                    "",
                    f"- Archive: `{conversation.archive_path}`",
                    f"- Archive SHA-256: `{conversation.archive_sha256}`",
                    f"- ZIP entry: `{conversation.ref.source_entry}`",
                    f"- Entry SHA-256: `{conversation.ref.source_sha256}`",
                    f"- Source size: {conversation.ref.source_size_bytes} bytes",
                    f"- JSON errors: {conversation.json_errors or 'none'}",
                    "",
                    "本笔记由可重建 parser 生成。事实回溯以 ZIP entry、ordinal、message_id/call_id 为准。",
                    "",
                ]
            )
        lines.extend([AUTOGEN_END, ""])
        rendered_body = "\n".join(lines)
        if manual_content.strip():
            return f"{rendered_body}\n{manual_content.strip()}\n"
        return f"{rendered_body}\n{DEFAULT_MANUAL_SECTION}"


def _infer_project(cwd: str) -> list[str]:
    if not cwd:
        return []
    norm = cwd.replace("\\", "/").rstrip("/").lower()
    if "research-memory-gateway" in norm or norm.endswith("/memory"):
        return ["research-memory-gateway"]
    if "cherry" in norm:
        return ["cherry-studio"]
    return []


def _infer_timeline(created_at: str) -> list[str]:
    date = _date_part(created_at)
    if date and len(date) >= 7:
        return [date[:7]]
    return []


def _date_part(value: str) -> str:
    return value[:10] if value and re.match(r"\d{4}-\d{2}-\d{2}", value) else ""


def _safe_filename(value: str) -> str:
    value = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "-", value)
    value = re.sub(r"\s+", " ", value).strip(" .")
    return (value[:180].rstrip(" .") or hashlib.sha256(value.encode()).hexdigest()[:16])


def _truncate_utf8(value: str, max_bytes: int) -> str:
    encoded = value.encode("utf-8")
    if len(encoded) <= max_bytes:
        return value
    return encoded[:max_bytes].decode("utf-8", errors="ignore")


def _table(value: str) -> str:
    return value.replace("|", "\\|").replace("\r", " ").replace("\n", "<br>")
